apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-npu-plugin
  labels:
    app: intel-npu-plugin
spec:
  selector:
    matchLabels:
      app: intel-npu-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: intel-npu-plugin
    spec:
      containers:
      - name: intel-npu-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-npu-plugin:0.34.0
        imagePullPolicy: IfNotPresent
        securityContext:
          seLinuxOptions:
            type: "container_device_plugin_t"
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "45Mi"
            cpu: 40m
          limits:
            memory: "90Mi"
            cpu: 100m
        volumeMounts:
        - name: devfs
          mountPath: /dev/accel
          readOnly: true
        - name: sysfsaccel
          mountPath: /sys/class/accel
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev/accel
      - name: sysfsaccel
        hostPath:
          path: /sys/class/accel
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/arch: amd64
