apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
spec:
  ipAddresses:
  - "127.0.0.1"
  privateKey:
    rotationPolicy: Always
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: xpum-server-cert
