// Copyright 2024 Intel Corporation. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: levelzero.proto

package gpulevelzero

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIntelIndicesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIntelIndicesMessage) Reset() {
	*x = GetIntelIndicesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntelIndicesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntelIndicesMessage) ProtoMessage() {}

func (x *GetIntelIndicesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntelIndicesMessage.ProtoReflect.Descriptor instead.
func (*GetIntelIndicesMessage) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{0}
}

type DeviceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BdfAddress string `protobuf:"bytes,1,opt,name=bdfAddress,proto3" json:"bdfAddress,omitempty"`
}

func (x *DeviceId) Reset() {
	*x = DeviceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceId) ProtoMessage() {}

func (x *DeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceId.ProtoReflect.Descriptor instead.
func (*DeviceId) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceId) GetBdfAddress() string {
	if x != nil {
		return x.BdfAddress
	}
	return ""
}

type DeviceHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryOk bool   `protobuf:"varint,1,opt,name=memory_ok,json=memoryOk,proto3" json:"memory_ok,omitempty"`
	BusOk    bool   `protobuf:"varint,2,opt,name=bus_ok,json=busOk,proto3" json:"bus_ok,omitempty"`
	SocOk    bool   `protobuf:"varint,3,opt,name=soc_ok,json=socOk,proto3" json:"soc_ok,omitempty"`
	Error    *Error `protobuf:"bytes,42,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeviceHealth) Reset() {
	*x = DeviceHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHealth) ProtoMessage() {}

func (x *DeviceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHealth.ProtoReflect.Descriptor instead.
func (*DeviceHealth) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceHealth) GetMemoryOk() bool {
	if x != nil {
		return x.MemoryOk
	}
	return false
}

func (x *DeviceHealth) GetBusOk() bool {
	if x != nil {
		return x.BusOk
	}
	return false
}

func (x *DeviceHealth) GetSocOk() bool {
	if x != nil {
		return x.SocOk
	}
	return false
}

func (x *DeviceHealth) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeviceTemperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Global float64 `protobuf:"fixed64,1,opt,name=global,proto3" json:"global,omitempty"`
	Gpu    float64 `protobuf:"fixed64,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Memory float64 `protobuf:"fixed64,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Error  *Error  `protobuf:"bytes,42,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeviceTemperature) Reset() {
	*x = DeviceTemperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceTemperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTemperature) ProtoMessage() {}

func (x *DeviceTemperature) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTemperature.ProtoReflect.Descriptor instead.
func (*DeviceTemperature) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceTemperature) GetGlobal() float64 {
	if x != nil {
		return x.Global
	}
	return 0
}

func (x *DeviceTemperature) GetGpu() float64 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

func (x *DeviceTemperature) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *DeviceTemperature) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeviceIndices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indices []uint32 `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Error   *Error   `protobuf:"bytes,42,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeviceIndices) Reset() {
	*x = DeviceIndices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceIndices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIndices) ProtoMessage() {}

func (x *DeviceIndices) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIndices.ProtoReflect.Descriptor instead.
func (*DeviceIndices) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceIndices) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *DeviceIndices) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeviceMemoryAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemorySize uint64 `protobuf:"varint,1,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	Error      *Error `protobuf:"bytes,42,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeviceMemoryAmount) Reset() {
	*x = DeviceMemoryAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceMemoryAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMemoryAmount) ProtoMessage() {}

func (x *DeviceMemoryAmount) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMemoryAmount.ProtoReflect.Descriptor instead.
func (*DeviceMemoryAmount) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceMemoryAmount) GetMemorySize() uint64 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *DeviceMemoryAmount) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Errorcode   uint32 `protobuf:"varint,2,opt,name=errorcode,proto3" json:"errorcode,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelzero_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_levelzero_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_levelzero_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Error) GetErrorcode() uint32 {
	if x != nil {
		return x.Errorcode
	}
	return 0
}

var File_levelzero_proto protoreflect.FileDescriptor

var file_levelzero_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x7a, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x08, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x64, 0x66, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x64, 0x66,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x77, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x4f, 0x6b, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x75, 0x73, 0x4f, 0x6b, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x6f, 0x63, 0x5f, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x6f, 0x63,
	0x4f, 0x6b, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x2a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x73, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x67, 0x70, 0x75, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x2a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73,
	0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x2a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x53,
	0x0a, 0x12, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x2a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xec, 0x01, 0x0a,
	0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x7a, 0x65, 0x72, 0x6f, 0x12, 0x2d, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x09, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x0d, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x09, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x12, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x49, 0x6e,
	0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6c,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x09, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x1a, 0x13, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x67,
	0x70, 0x75, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x7a, 0x65, 0x72, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_levelzero_proto_rawDescOnce sync.Once
	file_levelzero_proto_rawDescData = file_levelzero_proto_rawDesc
)

func file_levelzero_proto_rawDescGZIP() []byte {
	file_levelzero_proto_rawDescOnce.Do(func() {
		file_levelzero_proto_rawDescData = protoimpl.X.CompressGZIP(file_levelzero_proto_rawDescData)
	})
	return file_levelzero_proto_rawDescData
}

var file_levelzero_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_levelzero_proto_goTypes = []interface{}{
	(*GetIntelIndicesMessage)(nil), // 0: GetIntelIndicesMessage
	(*DeviceId)(nil),               // 1: DeviceId
	(*DeviceHealth)(nil),           // 2: DeviceHealth
	(*DeviceTemperature)(nil),      // 3: DeviceTemperature
	(*DeviceIndices)(nil),          // 4: DeviceIndices
	(*DeviceMemoryAmount)(nil),     // 5: DeviceMemoryAmount
	(*Error)(nil),                  // 6: Error
}
var file_levelzero_proto_depIdxs = []int32{
	6, // 0: DeviceHealth.error:type_name -> Error
	6, // 1: DeviceTemperature.error:type_name -> Error
	6, // 2: DeviceIndices.error:type_name -> Error
	6, // 3: DeviceMemoryAmount.error:type_name -> Error
	1, // 4: Levelzero.GetDeviceHealth:input_type -> DeviceId
	1, // 5: Levelzero.GetDeviceTemperature:input_type -> DeviceId
	0, // 6: Levelzero.GetIntelIndices:input_type -> GetIntelIndicesMessage
	1, // 7: Levelzero.GetDeviceMemoryAmount:input_type -> DeviceId
	2, // 8: Levelzero.GetDeviceHealth:output_type -> DeviceHealth
	3, // 9: Levelzero.GetDeviceTemperature:output_type -> DeviceTemperature
	4, // 10: Levelzero.GetIntelIndices:output_type -> DeviceIndices
	5, // 11: Levelzero.GetDeviceMemoryAmount:output_type -> DeviceMemoryAmount
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_levelzero_proto_init() }
func file_levelzero_proto_init() {
	if File_levelzero_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_levelzero_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIntelIndicesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelzero_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelzero_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelzero_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceTemperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelzero_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceIndices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelzero_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceMemoryAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelzero_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_levelzero_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_levelzero_proto_goTypes,
		DependencyIndexes: file_levelzero_proto_depIdxs,
		MessageInfos:      file_levelzero_proto_msgTypes,
	}.Build()
	File_levelzero_proto = out.File
	file_levelzero_proto_rawDesc = nil
	file_levelzero_proto_goTypes = nil
	file_levelzero_proto_depIdxs = nil
}
