//go:build !ignore_autogenerated

// Copyright 2020 Intel Corporation. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DlbDevicePlugin) DeepCopyInto(out *DlbDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DlbDevicePlugin.
func (in *DlbDevicePlugin) DeepCopy() *DlbDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(DlbDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DlbDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DlbDevicePluginList) DeepCopyInto(out *DlbDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DlbDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DlbDevicePluginList.
func (in *DlbDevicePluginList) DeepCopy() *DlbDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(DlbDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DlbDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DlbDevicePluginSpec) DeepCopyInto(out *DlbDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DlbDevicePluginSpec.
func (in *DlbDevicePluginSpec) DeepCopy() *DlbDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DlbDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DlbDevicePluginStatus) DeepCopyInto(out *DlbDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DlbDevicePluginStatus.
func (in *DlbDevicePluginStatus) DeepCopy() *DlbDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(DlbDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DsaDevicePlugin) DeepCopyInto(out *DsaDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DsaDevicePlugin.
func (in *DsaDevicePlugin) DeepCopy() *DsaDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(DsaDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DsaDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DsaDevicePluginList) DeepCopyInto(out *DsaDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DsaDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DsaDevicePluginList.
func (in *DsaDevicePluginList) DeepCopy() *DsaDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(DsaDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DsaDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DsaDevicePluginSpec) DeepCopyInto(out *DsaDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DsaDevicePluginSpec.
func (in *DsaDevicePluginSpec) DeepCopy() *DsaDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DsaDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DsaDevicePluginStatus) DeepCopyInto(out *DsaDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DsaDevicePluginStatus.
func (in *DsaDevicePluginStatus) DeepCopy() *DsaDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(DsaDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FpgaDevicePlugin) DeepCopyInto(out *FpgaDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FpgaDevicePlugin.
func (in *FpgaDevicePlugin) DeepCopy() *FpgaDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(FpgaDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FpgaDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FpgaDevicePluginList) DeepCopyInto(out *FpgaDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FpgaDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FpgaDevicePluginList.
func (in *FpgaDevicePluginList) DeepCopy() *FpgaDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(FpgaDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FpgaDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FpgaDevicePluginSpec) DeepCopyInto(out *FpgaDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FpgaDevicePluginSpec.
func (in *FpgaDevicePluginSpec) DeepCopy() *FpgaDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(FpgaDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FpgaDevicePluginStatus) DeepCopyInto(out *FpgaDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FpgaDevicePluginStatus.
func (in *FpgaDevicePluginStatus) DeepCopy() *FpgaDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(FpgaDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuDevicePlugin) DeepCopyInto(out *GpuDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuDevicePlugin.
func (in *GpuDevicePlugin) DeepCopy() *GpuDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(GpuDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuDevicePluginList) DeepCopyInto(out *GpuDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuDevicePluginList.
func (in *GpuDevicePluginList) DeepCopy() *GpuDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(GpuDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuDevicePluginSpec) DeepCopyInto(out *GpuDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuDevicePluginSpec.
func (in *GpuDevicePluginSpec) DeepCopy() *GpuDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(GpuDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuDevicePluginStatus) DeepCopyInto(out *GpuDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuDevicePluginStatus.
func (in *GpuDevicePluginStatus) DeepCopy() *GpuDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(GpuDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IaaDevicePlugin) DeepCopyInto(out *IaaDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IaaDevicePlugin.
func (in *IaaDevicePlugin) DeepCopy() *IaaDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(IaaDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IaaDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IaaDevicePluginList) DeepCopyInto(out *IaaDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IaaDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IaaDevicePluginList.
func (in *IaaDevicePluginList) DeepCopy() *IaaDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(IaaDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IaaDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IaaDevicePluginSpec) DeepCopyInto(out *IaaDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IaaDevicePluginSpec.
func (in *IaaDevicePluginSpec) DeepCopy() *IaaDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(IaaDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IaaDevicePluginStatus) DeepCopyInto(out *IaaDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IaaDevicePluginStatus.
func (in *IaaDevicePluginStatus) DeepCopy() *IaaDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(IaaDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QatDevicePlugin) DeepCopyInto(out *QatDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QatDevicePlugin.
func (in *QatDevicePlugin) DeepCopy() *QatDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(QatDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QatDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QatDevicePluginList) DeepCopyInto(out *QatDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QatDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QatDevicePluginList.
func (in *QatDevicePluginList) DeepCopy() *QatDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(QatDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QatDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QatDevicePluginSpec) DeepCopyInto(out *QatDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.KernelVfDrivers != nil {
		in, out := &in.KernelVfDrivers, &out.KernelVfDrivers
		*out = make([]KernelVfDriver, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QatDevicePluginSpec.
func (in *QatDevicePluginSpec) DeepCopy() *QatDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(QatDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QatDevicePluginStatus) DeepCopyInto(out *QatDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QatDevicePluginStatus.
func (in *QatDevicePluginStatus) DeepCopy() *QatDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(QatDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SgxDevicePlugin) DeepCopyInto(out *SgxDevicePlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SgxDevicePlugin.
func (in *SgxDevicePlugin) DeepCopy() *SgxDevicePlugin {
	if in == nil {
		return nil
	}
	out := new(SgxDevicePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SgxDevicePlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SgxDevicePluginList) DeepCopyInto(out *SgxDevicePluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SgxDevicePlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SgxDevicePluginList.
func (in *SgxDevicePluginList) DeepCopy() *SgxDevicePluginList {
	if in == nil {
		return nil
	}
	out := new(SgxDevicePluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SgxDevicePluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SgxDevicePluginSpec) DeepCopyInto(out *SgxDevicePluginSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SgxDevicePluginSpec.
func (in *SgxDevicePluginSpec) DeepCopy() *SgxDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(SgxDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SgxDevicePluginStatus) DeepCopyInto(out *SgxDevicePluginStatus) {
	*out = *in
	out.ControlledDaemonSet = in.ControlledDaemonSet
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SgxDevicePluginStatus.
func (in *SgxDevicePluginStatus) DeepCopy() *SgxDevicePluginStatus {
	if in == nil {
		return nil
	}
	out := new(SgxDevicePluginStatus)
	in.DeepCopyInto(out)
	return out
}
