run:
  tests: true
  build-tags:
    - kerneldrv

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomodguard
    - gosimple
    - gosec
    - govet
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.9
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 31

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # Until the testing package allows pinning variables disable scopelint
        # for tests. See https://github.com/kyoh86/scopelint/issues/4.
        - scopelint
