run:
  tests: true
  build-tags:
    - kerneldrv
  max-issues-per-linter: 0
  max-same-issues: 0
  skip-dirs:
    - cmd/vpu_plugin

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goimports
    - gomodguard
    - gosimple
    - gosec
    - govet
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - wsl

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.9
  govet:
    check-shadowing: true
    enable:
    - "fieldalignment"
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 31

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # Until the testing package allows pinning variables disable scopelint
        # for tests. See https://github.com/kyoh86/scopelint/issues/4.
        - scopelint
        - gocognit
