
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - d1c7b6d5.intel.com
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dsadeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dsadeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - sgxdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - sgxdeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fpga.intel.com
  resources:
  - acceleratorfunctions
  - fpgaregions
  verbs:
  - get
  - list
  - watch
