apiVersion: batch/v1
kind: Job
metadata:
  name: intelfpga-demo-job
  labels:
    jobgroup: intelfpga-demo
spec:
  template:
    metadata:
      labels:
        jobgroup: intelfpga-demo
    spec:
      restartPolicy: Never
      containers:
        - name: intelfpga-demo-job-1
          image: ubuntu-demo-opae:latest
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/run_hello_fpga.sh"]
          securityContext:
            capabilities:
              add:
                [IPC_LOCK]
          resources:
            limits:
              intel.com/fpga-d8424dc4a4a3c413f89e433683f9040b: 1
