apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-plugin
spec:
  template:
    spec:
      initContainers:
      - name: intel-qat-initcontainer
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-qat-initcontainer:0.26.0
        securityContext:
          readOnlyRootFilesystem: true
          privileged: true
        volumeMounts:
        - name: sysfs
          mountPath: /sys
        - name: qat-config
          mountPath: /qat-init/conf
      volumes:
      - name: sysfs
        hostPath:
          path: /sys
      - name: qat-config
        configMap:
          name: qat-config
          defaultMode: 0440
