apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-iaa-plugin
spec:
  template:
    spec:
      initContainers:
      - name: intel-iaa-initcontainer
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DEVICE_TYPE
            value: "iaa"
        image: intel/intel-idxd-config-initcontainer:0.32.1
        securityContext:
          seLinuxOptions:
            type: "container_device_plugin_init_t"
          readOnlyRootFilesystem: true
          privileged: true
        volumeMounts:
        - mountPath: /sys/bus/dsa
          name: sys-bus-dsa
        - mountPath: /sys/devices
          name: sys-devices
        - mountPath: /idxd-init/conf
          name: intel-iaa-config-volume
        - mountPath: /idxd-init/scratch
          name: scratch
      volumes:
      - name: sys-bus-dsa
        hostPath:
          path: /sys/bus/dsa
      - name: sys-devices
        hostPath:
          path: /sys/devices
      - name: intel-iaa-config-volume
        configMap:
          name: intel-iaa-config
      - name: scratch
        emptyDir: {}
