// Copyright 2018 Intel Corporation. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/intel/intel-device-plugins-for-kubernetes/pkg/apis/fpga.intel.com/v1"
	scheme "github.com/intel/intel-device-plugins-for-kubernetes/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AcceleratorFunctionsGetter has a method to return a AcceleratorFunctionInterface.
// A group's client should implement this interface.
type AcceleratorFunctionsGetter interface {
	AcceleratorFunctions(namespace string) AcceleratorFunctionInterface
}

// AcceleratorFunctionInterface has methods to work with AcceleratorFunction resources.
type AcceleratorFunctionInterface interface {
	Create(*v1.AcceleratorFunction) (*v1.AcceleratorFunction, error)
	Update(*v1.AcceleratorFunction) (*v1.AcceleratorFunction, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AcceleratorFunction, error)
	List(opts metav1.ListOptions) (*v1.AcceleratorFunctionList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AcceleratorFunction, err error)
	AcceleratorFunctionExpansion
}

// acceleratorFunctions implements AcceleratorFunctionInterface
type acceleratorFunctions struct {
	client rest.Interface
	ns     string
}

// newAcceleratorFunctions returns a AcceleratorFunctions
func newAcceleratorFunctions(c *FpgaV1Client, namespace string) *acceleratorFunctions {
	return &acceleratorFunctions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the acceleratorFunction, and returns the corresponding acceleratorFunction object, and an error if there is any.
func (c *acceleratorFunctions) Get(name string, options metav1.GetOptions) (result *v1.AcceleratorFunction, err error) {
	result = &v1.AcceleratorFunction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AcceleratorFunctions that match those selectors.
func (c *acceleratorFunctions) List(opts metav1.ListOptions) (result *v1.AcceleratorFunctionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AcceleratorFunctionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested acceleratorFunctions.
func (c *acceleratorFunctions) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a acceleratorFunction and creates it.  Returns the server's representation of the acceleratorFunction, and an error, if there is any.
func (c *acceleratorFunctions) Create(acceleratorFunction *v1.AcceleratorFunction) (result *v1.AcceleratorFunction, err error) {
	result = &v1.AcceleratorFunction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		Body(acceleratorFunction).
		Do().
		Into(result)
	return
}

// Update takes the representation of a acceleratorFunction and updates it. Returns the server's representation of the acceleratorFunction, and an error, if there is any.
func (c *acceleratorFunctions) Update(acceleratorFunction *v1.AcceleratorFunction) (result *v1.AcceleratorFunction, err error) {
	result = &v1.AcceleratorFunction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		Name(acceleratorFunction.Name).
		Body(acceleratorFunction).
		Do().
		Into(result)
	return
}

// Delete takes name of the acceleratorFunction and deletes it. Returns an error if one occurs.
func (c *acceleratorFunctions) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *acceleratorFunctions) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched acceleratorFunction.
func (c *acceleratorFunctions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AcceleratorFunction, err error) {
	result = &v1.AcceleratorFunction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("acceleratorfunctions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
