// Copyright 2018 Intel Corporation. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/intel/intel-device-plugins-for-kubernetes/pkg/apis/fpga.intel.com/v1"
	scheme "github.com/intel/intel-device-plugins-for-kubernetes/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FpgaRegionsGetter has a method to return a FpgaRegionInterface.
// A group's client should implement this interface.
type FpgaRegionsGetter interface {
	FpgaRegions(namespace string) FpgaRegionInterface
}

// FpgaRegionInterface has methods to work with FpgaRegion resources.
type FpgaRegionInterface interface {
	Create(*v1.FpgaRegion) (*v1.FpgaRegion, error)
	Update(*v1.FpgaRegion) (*v1.FpgaRegion, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.FpgaRegion, error)
	List(opts metav1.ListOptions) (*v1.FpgaRegionList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.FpgaRegion, err error)
	FpgaRegionExpansion
}

// fpgaRegions implements FpgaRegionInterface
type fpgaRegions struct {
	client rest.Interface
	ns     string
}

// newFpgaRegions returns a FpgaRegions
func newFpgaRegions(c *FpgaV1Client, namespace string) *fpgaRegions {
	return &fpgaRegions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fpgaRegion, and returns the corresponding fpgaRegion object, and an error if there is any.
func (c *fpgaRegions) Get(name string, options metav1.GetOptions) (result *v1.FpgaRegion, err error) {
	result = &v1.FpgaRegion{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fpgaregions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FpgaRegions that match those selectors.
func (c *fpgaRegions) List(opts metav1.ListOptions) (result *v1.FpgaRegionList, err error) {
	result = &v1.FpgaRegionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fpgaregions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fpgaRegions.
func (c *fpgaRegions) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fpgaregions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fpgaRegion and creates it.  Returns the server's representation of the fpgaRegion, and an error, if there is any.
func (c *fpgaRegions) Create(fpgaRegion *v1.FpgaRegion) (result *v1.FpgaRegion, err error) {
	result = &v1.FpgaRegion{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fpgaregions").
		Body(fpgaRegion).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fpgaRegion and updates it. Returns the server's representation of the fpgaRegion, and an error, if there is any.
func (c *fpgaRegions) Update(fpgaRegion *v1.FpgaRegion) (result *v1.FpgaRegion, err error) {
	result = &v1.FpgaRegion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fpgaregions").
		Name(fpgaRegion.Name).
		Body(fpgaRegion).
		Do().
		Into(result)
	return
}

// Delete takes name of the fpgaRegion and deletes it. Returns an error if one occurs.
func (c *fpgaRegions) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fpgaregions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fpgaRegions) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fpgaregions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fpgaRegion.
func (c *fpgaRegions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.FpgaRegion, err error) {
	result = &v1.FpgaRegion{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fpgaregions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
