apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: inteldeviceplugins-system
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      serviceAccountName: resource-reader-sa
      initContainers:
      - name: intel-gpu-initcontainer
        image: intel/intel-gpu-initcontainer:0.24.0
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /etc/kubernetes/node-feature-discovery/source.d/
          name: nfd-source-hooks
      containers:
      - name: intel-gpu-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-gpu-plugin:0.24.0
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        command: [
          "/usr/local/bin/intel_gpu_device_plugin",
          "-shared-dev-num", "300",
          "-enable-monitoring",
          "-resource-manager",
          "-v", "2"
        ]
        volumeMounts:
        - name: devfs
          mountPath: /dev/dri
          readOnly: true
        - name: sysfs
          mountPath: /sys/class/drm
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
        - name: podresources
          mountPath: /var/lib/kubelet/pod-resources
      volumes:
      - name: devfs
        hostPath:
          path: /dev/dri
      - name: sysfs
        hostPath:
          path: /sys/class/drm
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: podresources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      - name: nfd-source-hooks
        hostPath:
          path: /etc/kubernetes/node-feature-discovery/source.d/
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/arch: amd64
