apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-plugin
  labels:
    app: intel-qat-plugin
  annotations:
    container.apparmor.security.beta.kubernetes.io/intel-qat-plugin: unconfined
spec:
  selector:
    matchLabels:
      app: intel-qat-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: intel-qat-plugin
      annotations:
        container.apparmor.security.beta.kubernetes.io/intel-qat-plugin: unconfined
    spec:
      automountServiceAccountToken: false
      containers:
      - name: intel-qat-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-qat-plugin:0.31.1
        securityContext:
          seLinuxOptions:
            type: "container_device_plugin_t"
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "15Mi"
            cpu: 70m
          limits:
            memory: "30Mi"
            cpu: 140m
        volumeMounts:
        - name: devdir
          mountPath: /dev/vfio
          readOnly: true
        - name: debugfsdir
          mountPath: /sys/kernel/debug
          readOnly: true
        - name: pcidir
          mountPath: /sys/bus/pci
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devdir
        hostPath:
          path: /dev/vfio
      - name: debugfsdir
        hostPath:
          path: /sys/kernel/debug
      - name: pcidir
        hostPath:
          path: /sys/bus/pci
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/arch: amd64
