apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
      - name: intel-gpu-plugin
        args:
        - "-shared-dev-num=30"
        - "-enable-monitoring"
        - "-v=2"
