apiVersion: batch/v1
kind: Job
metadata:
  name: intelgpu-demo-job
  labels:
    jobgroup: intelgpu-demo
spec:
  template:
    metadata:
      labels:
        jobgroup: intelgpu-demo
    spec:
      restartPolicy: Never
      containers:
        -
          name: intelgpu-demo-job-1
          image: intel/intel-opencl-icd:devel
          imagePullPolicy: IfNotPresent
          command: [ "clinfo" ]
          resources:
            limits:
              gpu.intel.com/i915: 1
