// Copyright 2020 Intel Corporation. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/intel/intel-device-plugins-for-kubernetes/pkg/apis/fpga.intel.com/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FpgaRegionLister helps list FpgaRegions.
type FpgaRegionLister interface {
	// List lists all FpgaRegions in the indexer.
	List(selector labels.Selector) (ret []*v1.FpgaRegion, err error)
	// FpgaRegions returns an object that can list and get FpgaRegions.
	FpgaRegions(namespace string) FpgaRegionNamespaceLister
	FpgaRegionListerExpansion
}

// fpgaRegionLister implements the FpgaRegionLister interface.
type fpgaRegionLister struct {
	indexer cache.Indexer
}

// NewFpgaRegionLister returns a new FpgaRegionLister.
func NewFpgaRegionLister(indexer cache.Indexer) FpgaRegionLister {
	return &fpgaRegionLister{indexer: indexer}
}

// List lists all FpgaRegions in the indexer.
func (s *fpgaRegionLister) List(selector labels.Selector) (ret []*v1.FpgaRegion, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.FpgaRegion))
	})
	return ret, err
}

// FpgaRegions returns an object that can list and get FpgaRegions.
func (s *fpgaRegionLister) FpgaRegions(namespace string) FpgaRegionNamespaceLister {
	return fpgaRegionNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FpgaRegionNamespaceLister helps list and get FpgaRegions.
type FpgaRegionNamespaceLister interface {
	// List lists all FpgaRegions in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.FpgaRegion, err error)
	// Get retrieves the FpgaRegion from the indexer for a given namespace and name.
	Get(name string) (*v1.FpgaRegion, error)
	FpgaRegionNamespaceListerExpansion
}

// fpgaRegionNamespaceLister implements the FpgaRegionNamespaceLister
// interface.
type fpgaRegionNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FpgaRegions in the indexer for a given namespace.
func (s fpgaRegionNamespaceLister) List(selector labels.Selector) (ret []*v1.FpgaRegion, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.FpgaRegion))
	})
	return ret, err
}

// Get retrieves the FpgaRegion from the indexer for a given namespace and name.
func (s fpgaRegionNamespaceLister) Get(name string) (*v1.FpgaRegion, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("fpgaregion"), name)
	}
	return obj.(*v1.FpgaRegion), nil
}
