apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-iaa-plugin
  labels:
    app: intel-iaa-plugin
spec:
  selector:
    matchLabels:
      app: intel-iaa-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: intel-iaa-plugin
    spec:
      automountServiceAccountToken: false
      containers:
      - name: intel-iaa-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-iaa-plugin:devel
        imagePullPolicy: IfNotPresent
        securityContext:
          seLinuxOptions:
            type: "container_device_plugin_t"
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: devfs
          mountPath: /dev/iax
          readOnly: true
        - name: chardevs
          mountPath: /dev/char
          readOnly: true
        - name: sysfs
          mountPath: /sys/bus/dsa/devices
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev/iax
      - name: chardevs
        hostPath:
          path: /dev/char
      - name: sysfs
        hostPath:
          path: /sys/bus/dsa/devices
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/arch: amd64
