apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.9.0"

configMapGenerator:
- name: nfd-worker-conf
  namespace: node-feature-discovery
  behavior: replace
  files:
  - nfd-worker.conf
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nfd-master
  path: master-args.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: nfd-master
  path: master-rbac.yaml
