apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpudeviceplugin-sample
spec:
  image: intel/intel-gpu-plugin:0.27.1
  sharedDevNum: 10
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
