apiVersion: deviceplugin.intel.com/v1
kind: DlbDevicePlugin
metadata:
  name: dlbdeviceplugin-sample
spec:
  image: intel/intel-dlb-plugin:0.34.0
  initImage: intel/intel-dlb-initcontainer:0.34.0
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/dlb: 'true'
