apiVersion: deviceplugin.intel.com/v1
kind: DsaDevicePlugin
metadata:
  name: dsadeviceplugin-sample
spec:
  image: intel/intel-dsa-plugin:0.25.0
  sharedDevNum: 10
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/dsa: 'true'
