apiVersion: deviceplugin.intel.com/v1
kind: FpgaDevicePlugin
metadata:
  name: fpgadeviceplugin-sample
spec:
  image: intel/intel-fpga-plugin:0.31.0
  initImage: intel/intel-fpga-initcontainer:0.31.0
  mode: region
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/fpga-arria10: 'true'
