apiVersion: v1
kind: Pod
metadata:
  name: intelgpu-demo-pod
spec:
  containers:
    -
      name: intelgpu-demo-container-1
      image: ubuntu-demo-opencl:latest
      imagePullPolicy: IfNotPresent
      command: [ "/run_beignet_tests.sh", "/workspace/beignet/build/utests" ]
      resources:
        limits:
          intel.com/gpu: 1
