apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: intel-xpumanager
  name: intel-xpumanager
spec:
  template:
    spec:
      volumes:
        - name: features-d
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d/"
      containers:
      - name: xelink-sidecar
        image: intel/intel-xpumanager-sidecar:0.34.0
        imagePullPolicy: IfNotPresent
        args:
          - -v=2
        volumeMounts:
        - name: features-d
          mountPath: "/etc/kubernetes/node-feature-discovery/features.d/"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0
