// Copyright 2018 Intel Corporation. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	fpgaintelcomv1 "github.com/intel/intel-device-plugins-for-kubernetes/pkg/apis/fpga.intel.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAcceleratorFunctions implements AcceleratorFunctionInterface
type FakeAcceleratorFunctions struct {
	Fake *FakeFpgaV1
	ns   string
}

var acceleratorfunctionsResource = schema.GroupVersionResource{Group: "fpga.intel.com", Version: "v1", Resource: "acceleratorfunctions"}

var acceleratorfunctionsKind = schema.GroupVersionKind{Group: "fpga.intel.com", Version: "v1", Kind: "AcceleratorFunction"}

// Get takes name of the acceleratorFunction, and returns the corresponding acceleratorFunction object, and an error if there is any.
func (c *FakeAcceleratorFunctions) Get(name string, options v1.GetOptions) (result *fpgaintelcomv1.AcceleratorFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(acceleratorfunctionsResource, c.ns, name), &fpgaintelcomv1.AcceleratorFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fpgaintelcomv1.AcceleratorFunction), err
}

// List takes label and field selectors, and returns the list of AcceleratorFunctions that match those selectors.
func (c *FakeAcceleratorFunctions) List(opts v1.ListOptions) (result *fpgaintelcomv1.AcceleratorFunctionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(acceleratorfunctionsResource, acceleratorfunctionsKind, c.ns, opts), &fpgaintelcomv1.AcceleratorFunctionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &fpgaintelcomv1.AcceleratorFunctionList{ListMeta: obj.(*fpgaintelcomv1.AcceleratorFunctionList).ListMeta}
	for _, item := range obj.(*fpgaintelcomv1.AcceleratorFunctionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested acceleratorFunctions.
func (c *FakeAcceleratorFunctions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(acceleratorfunctionsResource, c.ns, opts))

}

// Create takes the representation of a acceleratorFunction and creates it.  Returns the server's representation of the acceleratorFunction, and an error, if there is any.
func (c *FakeAcceleratorFunctions) Create(acceleratorFunction *fpgaintelcomv1.AcceleratorFunction) (result *fpgaintelcomv1.AcceleratorFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(acceleratorfunctionsResource, c.ns, acceleratorFunction), &fpgaintelcomv1.AcceleratorFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fpgaintelcomv1.AcceleratorFunction), err
}

// Update takes the representation of a acceleratorFunction and updates it. Returns the server's representation of the acceleratorFunction, and an error, if there is any.
func (c *FakeAcceleratorFunctions) Update(acceleratorFunction *fpgaintelcomv1.AcceleratorFunction) (result *fpgaintelcomv1.AcceleratorFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(acceleratorfunctionsResource, c.ns, acceleratorFunction), &fpgaintelcomv1.AcceleratorFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fpgaintelcomv1.AcceleratorFunction), err
}

// Delete takes name of the acceleratorFunction and deletes it. Returns an error if one occurs.
func (c *FakeAcceleratorFunctions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(acceleratorfunctionsResource, c.ns, name), &fpgaintelcomv1.AcceleratorFunction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAcceleratorFunctions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(acceleratorfunctionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &fpgaintelcomv1.AcceleratorFunctionList{})
	return err
}

// Patch applies the patch and returns the patched acceleratorFunction.
func (c *FakeAcceleratorFunctions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *fpgaintelcomv1.AcceleratorFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(acceleratorfunctionsResource, c.ns, name, pt, data, subresources...), &fpgaintelcomv1.AcceleratorFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fpgaintelcomv1.AcceleratorFunction), err
}
