apiVersion: v1
kind: Pod
metadata:
  name: dlb-libdlb-demo
spec:
  restartPolicy: Never
  containers:
  - name: pf
    image: intel/dlb-libdlb-demo:devel
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        dlb.intel.com/pf: 1
        cpu: 1
      requests:
        dlb.intel.com/pf: 1
        cpu: 1
  - name: vf
    image: intel/dlb-libdlb-demo:devel
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        dlb.intel.com/vf: 1
        cpu: 1
      requests:
        dlb.intel.com/vf: 1
        cpu: 1
