apiVersion: batch/v1
kind: Job
metadata:
  name: intelfpga-demo-job
  labels:
    jobgroup: intelfpga-demo
spec:
  template:
    metadata:
      labels:
        jobgroup: intelfpga-demo
    spec:
      restartPolicy: Never
      containers:
        - name: intelfpga-demo-job-1
          image: intel/opae-nlb-demo:0.31.1
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                [IPC_LOCK]
          resources:
            limits:
              cpu: 1
              hugepages-2Mi: 20Mi
              fpga.intel.com/af-d8424dc4a4a3c413f89e433683f9040b: 1
