apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-sgx-plugin
spec:
  template:
    spec:
      initContainers:
      - name: intel-sgx-initcontainer
        image: intel/intel-sgx-initcontainer:0.24.0
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /etc/kubernetes/node-feature-discovery/source.d/
          name: nfd-source-hooks
      volumes:
      - name: nfd-source-hooks
        hostPath:
          path: /etc/kubernetes/node-feature-discovery/source.d/
          type: DirectoryOrCreate
