apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadvisor
  name: cadvisor
  namespace: cadvisor
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: cadvisor
