apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-dlb-plugin
  labels:
    app: intel-dlb-plugin
spec:
  selector:
    matchLabels:
      app: intel-dlb-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: intel-dlb-plugin
    spec:
      automountServiceAccountToken: false
      containers:
      - name: intel-dlb-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-dlb-plugin:0.34.0
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /tmp/termination-log
        resources:
          requests:
            memory: "15Mi"
            cpu: 40m
          limits:
            memory: "30Mi"
            cpu: 100m
        volumeMounts:
        - name: devfs
          mountPath: /dev
          readOnly: true
        - name: sysfs
          mountPath: /sys/class/dlb2
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sysfs
        hostPath:
          path: /sys/class/dlb2
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/arch: amd64
