name: publish
on:
  workflow_call:
    inputs:
      image_tag:
        default: "devel"
        required: false
        type: string
      registry:
        default: "docker.io/intel"
        required: false
        type: string
env:
  no_base_check: "['intel-idxd-config-initcontainer', 'crypto-perf', 'opae-nlb-demo', 'intel-gpu-levelzero']"

permissions:
  contents: read
  id-token: write

jobs:
  av_database:
    name: Download AV database
    runs-on: ubuntu-22.04
    steps:
      - name: Install clamav and update databases
        run: |
          sudo apt-get update -y
          sudo apt-get -y --no-install-recommends install clamav ca-certificates
          sudo systemctl stop clamav-freshclam.service
          sudo freshclam
      - name: Cache clamav databases
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /var/lib/clamav
          key: clamav-${{ github.run_id }}
  image:
    name: Build image
    needs: av_database
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - intel-gpu-initcontainer
          - intel-gpu-plugin
          - intel-gpu-levelzero
          - intel-qat-initcontainer
          - intel-qat-plugin
          - intel-deviceplugin-operator
          - intel-sgx-admissionwebhook
          - intel-sgx-plugin
          - intel-sgx-initcontainer
          - intel-dsa-plugin
          - intel-iaa-plugin
          - intel-idxd-config-initcontainer
          - intel-npu-plugin
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v5
        with:
          go-version-file: go.mod
          check-latest: true
      - run: make -e vendor
      - name: Build image
        env:
          IMAGE_NAME: ${{ matrix.image }}
        run: |
          ORG=${{ inputs.registry }} TAG=${{ inputs.image_tag }} make ${IMAGE_NAME} BUILDER=docker
      - name: Trivy scan for image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          scan-type: image
          image-ref: ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
          exit-code: 1
      - name: Prepare cache directory
        run: |
          sudo mkdir -p /var/lib/clamav
          sudo chmod a+rwx /var/lib/clamav
      - name: Retrieve AV database
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /var/lib/clamav
          key: clamav-${{ github.run_id }}
      - name: Malware scan
        env:
          FULL_IMAGE: ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
          IMG_FILE: ${{ matrix.image }}-${{ inputs.image_tag }}.tar
        run: |
          sudo apt-get update -y
          sudo apt-get -y --no-install-recommends install clamav ca-certificates
          sudo systemctl stop clamav-freshclam.service
          sudo freshclam
          docker save $FULL_IMAGE -o $IMG_FILE
          clamscan $IMG_FILE
      - name: Test image base layer
        # Don't run base layer check for selected images
        if: ${{ !contains(fromJson(env.no_base_check), matrix.image) }}
        run: IMG=${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }} make test-image-base-layer BUILDER=docker
      - name: Login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Push
        run: docker push ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
      - name: Get image digest
        if: ${{ inputs.image_tag != 'devel' }}
        id: digest
        run: |
          echo "image_sha=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }})" >> $GITHUB_OUTPUT
      - name: Install cosign
        if: ${{ inputs.image_tag != 'devel' }}
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 #v4.1.2
      - name: Keyless image sign
        if: ${{ inputs.image_tag != 'devel' }}
        run: |
          cosign sign --yes ${{ steps.digest.outputs.image_sha }}
