name: Publish

on:
  push:
    branches:
        - docs-add-sphinx-support

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools
        pip3 install --user -r requirements.txt
    - name: Branch off base for updated gh-pages
      run: |
        git branch gh-pages
        git checkout gh-pages
    - name: Add latest generated docs to gh-pages
      shell: bash
      run: |
        PATH="$HOME/.local/bin:$PATH" make html
        mkdir $HOME/output
        mv -v _build/html/* $HOME/output
        cd $HOME/output
        touch .nojekyll
        git init
        git add .
        author=$(git log --merges --pretty=format:%an -n 1)
        email=$(git log --merges --pretty=format:%ae -n 1)
        git config --global user.name "$author"
        git config --global user.email "$email"
        git commit -m "publish-docs.yml: generated latest html output." .
    - name: Publish/force-push to gh-pages
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages