name: Publish

on:
  push:
    branches:
        - docs-add-sphinx-support

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools
        pip3 install --user -r requirements.txt
    - name: Branch off base for updated gh-pages
      run: |
        git branch gh-pages
        git checkout gh-pages
    - name: Build docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make html
    - name: Deploy docs
      run: |
        mkdir $HOME/output
        mv -v _build/html/* $HOME/output
        touch $HOME/output/.nojekyll
        cd $HOME/output
        git init
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "generated latest html output."
        git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages